// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treePatch13 = new Entity("tree Patch")
engine.addEntity(treePatch13)
const treePatch13transform = new Transform({
  position: new Vector3(40, 0, -16),
  rotation: new Quaternion(0, -0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
treePatch13.addComponentOrReplace(treePatch13transform)
const treePatch13GLTFShape = new GLTFShape("models/contest3/treePatch.glb")
treePatch13GLTFShape.withCollisions = true
treePatch13GLTFShape.isPointerBlocker = true
treePatch13GLTFShape.visible = true
treePatch13.addComponentOrReplace(treePatch13GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fountain14 = new Entity("fountain")
engine.addEntity(fountain14)
const fountain14transform = new Transform({
  position: new Vector3(39, 0, -16),
  rotation: new Quaternion(0, 0.5372996, 0, 0.8433914),
  scale: new Vector3(1.5, 1.5, 1.5)
})
fountain14.addComponentOrReplace(fountain14transform)
const fountain14GLTFShape = new GLTFShape("models/contest3/fountain.glb")
fountain14GLTFShape.withCollisions = true
fountain14GLTFShape.isPointerBlocker = true
fountain14GLTFShape.visible = true
fountain14.addComponentOrReplace(fountain14GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pathWay19 = new Entity("path Way")
engine.addEntity(pathWay19)
const pathWay19transform = new Transform({
  position: new Vector3(24, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
pathWay19.addComponentOrReplace(pathWay19transform)
const pathWay19GLTFShape = new GLTFShape("models/common/pathWay.glb")
pathWay19GLTFShape.withCollisions = true
pathWay19GLTFShape.isPointerBlocker = true
pathWay19GLTFShape.visible = true
pathWay19.addComponentOrReplace(pathWay19GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0121 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0121)
const floorBaseGrass0121transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0121.addComponentOrReplace(floorBaseGrass0121transform)
const floorBaseGrass0121GLTFShape = new GLTFShape("models/common/grass/FloorBaseGrass_01.glb")
floorBaseGrass0121GLTFShape.withCollisions = true
floorBaseGrass0121GLTFShape.isPointerBlocker = true
floorBaseGrass0121GLTFShape.visible = true
floorBaseGrass0121.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0122 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0122)
const floorBaseGrass0122transform = new Transform({
  position: new Vector3(24, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0122.addComponentOrReplace(floorBaseGrass0122transform)
floorBaseGrass0122.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0123 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0123)
const floorBaseGrass0123transform = new Transform({
  position: new Vector3(40, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0123.addComponentOrReplace(floorBaseGrass0123transform)
floorBaseGrass0123.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0124 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0124)
const floorBaseGrass0124transform = new Transform({
  position: new Vector3(8, 0, -8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0124.addComponentOrReplace(floorBaseGrass0124transform)
floorBaseGrass0124.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0125 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0125)
const floorBaseGrass0125transform = new Transform({
  position: new Vector3(24, 0, -8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0125.addComponentOrReplace(floorBaseGrass0125transform)
floorBaseGrass0125.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0126 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0126)
const floorBaseGrass0126transform = new Transform({
  position: new Vector3(40, 0, -8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0126.addComponentOrReplace(floorBaseGrass0126transform)
floorBaseGrass0126.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0127 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0127)
const floorBaseGrass0127transform = new Transform({
  position: new Vector3(40, 0, -24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0127.addComponentOrReplace(floorBaseGrass0127transform)
floorBaseGrass0127.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0128 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0128)
const floorBaseGrass0128transform = new Transform({
  position: new Vector3(24, 0, -24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0128.addComponentOrReplace(floorBaseGrass0128transform)
floorBaseGrass0128.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0129 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0129)
const floorBaseGrass0129transform = new Transform({
  position: new Vector3(8, 0, -24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0129.addComponentOrReplace(floorBaseGrass0129transform)
floorBaseGrass0129.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0130 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0130)
const floorBaseGrass0130transform = new Transform({
  position: new Vector3(8, 0, -40),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0130.addComponentOrReplace(floorBaseGrass0130transform)
floorBaseGrass0130.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0131 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0131)
const floorBaseGrass0131transform = new Transform({
  position: new Vector3(24, 0, -40),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0131.addComponentOrReplace(floorBaseGrass0131transform)
floorBaseGrass0131.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0132 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0132)
const floorBaseGrass0132transform = new Transform({
  position: new Vector3(24, 0, -56),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0132.addComponentOrReplace(floorBaseGrass0132transform)
floorBaseGrass0132.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0133 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0133)
const floorBaseGrass0133transform = new Transform({
  position: new Vector3(24, 0, -72),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0133.addComponentOrReplace(floorBaseGrass0133transform)
floorBaseGrass0133.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const githubLink134 = new Entity("github Link1")
engine.addEntity(githubLink134)
const githubLink134transform = new Transform({
  position: new Vector3(21.35, 1.25, 8.63),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
githubLink134.addComponentOrReplace(githubLink134transform)
const githubLink134GLTFShape = new GLTFShape("models/common/separate-models/githubLink.glb")
githubLink134GLTFShape.withCollisions = true
githubLink134GLTFShape.isPointerBlocker = true
githubLink134GLTFShape.visible = true
githubLink134.addComponentOrReplace(githubLink134GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const twitterLink135 = new Entity("twitter Link 1")
engine.addEntity(twitterLink135)
const twitterLink135transform = new Transform({
  position: new Vector3(21.35, 1.25, 7.373),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
twitterLink135.addComponentOrReplace(twitterLink135transform)
const twitterLink135GLTFShape = new GLTFShape("models/common/separate-models/twitterLink.glb")
twitterLink135GLTFShape.withCollisions = true
twitterLink135GLTFShape.isPointerBlocker = true
twitterLink135GLTFShape.visible = true
twitterLink135.addComponentOrReplace(twitterLink135GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const githubLink236 = new Entity("github Link 2")
engine.addEntity(githubLink236)
const githubLink236transform = new Transform({
  position: new Vector3(21.35, 1.25, -15.37),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
githubLink236.addComponentOrReplace(githubLink236transform)
githubLink236.addComponentOrReplace(githubLink134GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const twitterLink237 = new Entity("twitter Link 2")
engine.addEntity(twitterLink237)
const twitterLink237transform = new Transform({
  position: new Vector3(21.35, 1.25, -16.63),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
twitterLink237.addComponentOrReplace(twitterLink237transform)
twitterLink237.addComponentOrReplace(twitterLink135GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const githubLink338 = new Entity("github Link 3")
engine.addEntity(githubLink338)
const githubLink338transform = new Transform({
  position: new Vector3(21.35, 1.25, -47.38),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
githubLink338.addComponentOrReplace(githubLink338transform)
githubLink338.addComponentOrReplace(githubLink134GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const twitterLink339 = new Entity("twitter Link 3")
engine.addEntity(twitterLink339)
const twitterLink339transform = new Transform({
  position: new Vector3(21.35, 1.25, -48.63),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
twitterLink339.addComponentOrReplace(twitterLink339transform)
twitterLink339.addComponentOrReplace(twitterLink135GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fountainAssetDisplay40 = new Entity("fountain Asset Display")
engine.addEntity(fountainAssetDisplay40)
const fountainAssetDisplay40transform = new Transform({
  position: new Vector3(14.5, 0.02, -16),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
fountainAssetDisplay40.addComponentOrReplace(fountainAssetDisplay40transform)
const fountainAssetDisplay40GLTFShape = new GLTFShape("models/contest3/fountainAssetDisplay.glb")
fountainAssetDisplay40GLTFShape.withCollisions = true
fountainAssetDisplay40GLTFShape.isPointerBlocker = true
fountainAssetDisplay40GLTFShape.visible = true
fountainAssetDisplay40.addComponentOrReplace(fountainAssetDisplay40GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const island41 = new Entity("island")
engine.addEntity(island41)
const island41transform = new Transform({
  position: new Vector3(48, 0, -48),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
island41.addComponentOrReplace(island41transform)
const island41GLTFShape = new GLTFShape("models/contest4/island.glb")
island41GLTFShape.withCollisions = true
island41GLTFShape.isPointerBlocker = true
island41GLTFShape.visible = true
island41.addComponentOrReplace(island41GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const islandAssetDisplay42 = new Entity("island Asset Display")
engine.addEntity(islandAssetDisplay42)
const islandAssetDisplay42transform = new Transform({
  position: new Vector3(11, 0, -48),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
islandAssetDisplay42.addComponentOrReplace(islandAssetDisplay42transform)
const islandAssetDisplay42GLTFShape = new GLTFShape("models/contest4/islandAssetDisplay.glb")
islandAssetDisplay42GLTFShape.withCollisions = true
islandAssetDisplay42GLTFShape.isPointerBlocker = true
islandAssetDisplay42GLTFShape.visible = true
islandAssetDisplay42.addComponentOrReplace(islandAssetDisplay42GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0143 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0143)
const floorBaseGrass0143transform = new Transform({
  position: new Vector3(8, 0, -56),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0143.addComponentOrReplace(floorBaseGrass0143transform)
floorBaseGrass0143.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const islandWalls44 = new Entity("island Walls")
engine.addEntity(islandWalls44)
const islandWalls44transform = new Transform({
  position: new Vector3(48, 0, -48),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
islandWalls44.addComponentOrReplace(islandWalls44transform)
const islandWalls44GLTFShape = new GLTFShape("models/contest4/islandWalls.glb")
islandWalls44GLTFShape.withCollisions = true
islandWalls44GLTFShape.isPointerBlocker = true
islandWalls44GLTFShape.visible = true
islandWalls44.addComponentOrReplace(islandWalls44GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const sleighWithScene45 = new Entity("sleigh With Scene")
engine.addEntity(sleighWithScene45)
const sleighWithScene45transform = new Transform({
  position: new Vector3(40, 0, -80),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
sleighWithScene45.addComponentOrReplace(sleighWithScene45transform)
const sleighWithScene45GLTFShape = new GLTFShape("models/contest6/sleighWithScene.glb")
sleighWithScene45GLTFShape.withCollisions = true
sleighWithScene45GLTFShape.isPointerBlocker = true
sleighWithScene45GLTFShape.visible = true
sleighWithScene45.addComponentOrReplace(sleighWithScene45GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0146 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0146)
const floorBaseGrass0146transform = new Transform({
  position: new Vector3(8, 0, -72),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0146.addComponentOrReplace(floorBaseGrass0146transform)
floorBaseGrass0146.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0147 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0147)
const floorBaseGrass0147transform = new Transform({
  position: new Vector3(8, 0, -88),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0147.addComponentOrReplace(floorBaseGrass0147transform)
floorBaseGrass0147.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0148 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0148)
const floorBaseGrass0148transform = new Transform({
  position: new Vector3(24, 0, -88),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0148.addComponentOrReplace(floorBaseGrass0148transform)
floorBaseGrass0148.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0149 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0149)
const floorBaseGrass0149transform = new Transform({
  position: new Vector3(40, 0, -72),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0149.addComponentOrReplace(floorBaseGrass0149transform)
floorBaseGrass0149.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0150 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0150)
const floorBaseGrass0150transform = new Transform({
  position: new Vector3(40, 0, -88),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0150.addComponentOrReplace(floorBaseGrass0150transform)
floorBaseGrass0150.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
  fountain:{
    entity: fountain14,
    transform: fountain14transform,
    GLTFShape: fountain14GLTFShape,
  },
  githubLink1:{
    entity: githubLink134,
    transform: githubLink134transform,
    GLTFShape: githubLink134GLTFShape,
  },
  twitterLink1:{
    entity: twitterLink135,
    transform: twitterLink135transform,
    GLTFShape: twitterLink135GLTFShape,
  },
  githubLink2:{
    entity: githubLink236,
    transform: githubLink236transform,
    GLTFShape: githubLink134GLTFShape,
  },
  twitterLink2:{
    entity: twitterLink237,
    transform: twitterLink237transform,
    GLTFShape: twitterLink135GLTFShape,
  },
  githubLink3:{
    entity: githubLink338,
    transform: githubLink338transform,
    GLTFShape: githubLink134GLTFShape,
  },
  twitterLink3:{
    entity: twitterLink339,
    transform: twitterLink339transform,
    GLTFShape: twitterLink135GLTFShape,
  },
  islandWalls:{
    entity: islandWalls44,
    transform: islandWalls44transform,
    GLTFShape: islandWalls44GLTFShape,
  },
}

