// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treePatch13 = new Entity("tree Patch")
engine.addEntity(treePatch13)
const treePatch13transform = new Transform({
  position: new Vector3(40, 0, -16),
  rotation: new Quaternion(0, -0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
treePatch13.addComponentOrReplace(treePatch13transform)
const treePatch13GLTFShape = new GLTFShape("models/contest3/treePatch.glb")
treePatch13GLTFShape.withCollisions = true
treePatch13GLTFShape.isPointerBlocker = true
treePatch13GLTFShape.visible = true
treePatch13.addComponentOrReplace(treePatch13GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fountain14 = new Entity("fountain")
engine.addEntity(fountain14)
const fountain14transform = new Transform({
  position: new Vector3(39, 0, -16),
  rotation: new Quaternion(0, 0.5372996, 0, 0.8433914),
  scale: new Vector3(1.5, 1.5, 1.5)
})
fountain14.addComponentOrReplace(fountain14transform)
const fountain14GLTFShape = new GLTFShape("models/contest3/fountain.glb")
fountain14GLTFShape.withCollisions = true
fountain14GLTFShape.isPointerBlocker = true
fountain14GLTFShape.visible = true
fountain14.addComponentOrReplace(fountain14GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pathWay19 = new Entity("path Way")
engine.addEntity(pathWay19)
const pathWay19transform = new Transform({
  position: new Vector3(24, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
pathWay19.addComponentOrReplace(pathWay19transform)
const pathWay19GLTFShape = new GLTFShape("models/common/pathWay.glb")
pathWay19GLTFShape.withCollisions = true
pathWay19GLTFShape.isPointerBlocker = true
pathWay19GLTFShape.visible = true
pathWay19.addComponentOrReplace(pathWay19GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0121 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0121)
const floorBaseGrass0121transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0121.addComponentOrReplace(floorBaseGrass0121transform)
const floorBaseGrass0121GLTFShape = new GLTFShape("models/common/grass/FloorBaseGrass_01.glb")
floorBaseGrass0121GLTFShape.withCollisions = true
floorBaseGrass0121GLTFShape.isPointerBlocker = true
floorBaseGrass0121GLTFShape.visible = true
floorBaseGrass0121.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0122 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0122)
const floorBaseGrass0122transform = new Transform({
  position: new Vector3(24, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0122.addComponentOrReplace(floorBaseGrass0122transform)
floorBaseGrass0122.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0123 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0123)
const floorBaseGrass0123transform = new Transform({
  position: new Vector3(40, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0123.addComponentOrReplace(floorBaseGrass0123transform)
floorBaseGrass0123.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0124 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0124)
const floorBaseGrass0124transform = new Transform({
  position: new Vector3(8, 0, -8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0124.addComponentOrReplace(floorBaseGrass0124transform)
floorBaseGrass0124.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0125 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0125)
const floorBaseGrass0125transform = new Transform({
  position: new Vector3(24, 0, -8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0125.addComponentOrReplace(floorBaseGrass0125transform)
floorBaseGrass0125.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0126 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0126)
const floorBaseGrass0126transform = new Transform({
  position: new Vector3(40, 0, -8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0126.addComponentOrReplace(floorBaseGrass0126transform)
floorBaseGrass0126.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0127 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0127)
const floorBaseGrass0127transform = new Transform({
  position: new Vector3(40, 0, -24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0127.addComponentOrReplace(floorBaseGrass0127transform)
floorBaseGrass0127.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0128 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0128)
const floorBaseGrass0128transform = new Transform({
  position: new Vector3(24, 0, -24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0128.addComponentOrReplace(floorBaseGrass0128transform)
floorBaseGrass0128.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0129 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0129)
const floorBaseGrass0129transform = new Transform({
  position: new Vector3(8, 0, -24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0129.addComponentOrReplace(floorBaseGrass0129transform)
floorBaseGrass0129.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0130 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0130)
const floorBaseGrass0130transform = new Transform({
  position: new Vector3(8, 0, -40),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0130.addComponentOrReplace(floorBaseGrass0130transform)
floorBaseGrass0130.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0131 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0131)
const floorBaseGrass0131transform = new Transform({
  position: new Vector3(24, 0, -40),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0131.addComponentOrReplace(floorBaseGrass0131transform)
floorBaseGrass0131.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0132 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0132)
const floorBaseGrass0132transform = new Transform({
  position: new Vector3(24, 0, -56),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0132.addComponentOrReplace(floorBaseGrass0132transform)
floorBaseGrass0132.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0133 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0133)
const floorBaseGrass0133transform = new Transform({
  position: new Vector3(24, 0, -72),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0133.addComponentOrReplace(floorBaseGrass0133transform)
floorBaseGrass0133.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fountainAssetDisplay40 = new Entity("fountain Asset Display")
engine.addEntity(fountainAssetDisplay40)
const fountainAssetDisplay40transform = new Transform({
  position: new Vector3(14.5, 0.02, -16),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
fountainAssetDisplay40.addComponentOrReplace(fountainAssetDisplay40transform)
const fountainAssetDisplay40GLTFShape = new GLTFShape("models/contest3/fountainAssetDisplay.glb")
fountainAssetDisplay40GLTFShape.withCollisions = true
fountainAssetDisplay40GLTFShape.isPointerBlocker = true
fountainAssetDisplay40GLTFShape.visible = true
fountainAssetDisplay40.addComponentOrReplace(fountainAssetDisplay40GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const island41 = new Entity("island")
engine.addEntity(island41)
const island41transform = new Transform({
  position: new Vector3(48, 0, -48),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
island41.addComponentOrReplace(island41transform)
const island41GLTFShape = new GLTFShape("models/contest4/island.glb")
island41GLTFShape.withCollisions = true
island41GLTFShape.isPointerBlocker = true
island41GLTFShape.visible = true
island41.addComponentOrReplace(island41GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const islandAssetDisplay42 = new Entity("island Asset Display")
engine.addEntity(islandAssetDisplay42)
const islandAssetDisplay42transform = new Transform({
  position: new Vector3(11, 0, -48),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
islandAssetDisplay42.addComponentOrReplace(islandAssetDisplay42transform)
const islandAssetDisplay42GLTFShape = new GLTFShape("models/contest4/islandAssetDisplay.glb")
islandAssetDisplay42GLTFShape.withCollisions = true
islandAssetDisplay42GLTFShape.isPointerBlocker = true
islandAssetDisplay42GLTFShape.visible = true
islandAssetDisplay42.addComponentOrReplace(islandAssetDisplay42GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0143 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0143)
const floorBaseGrass0143transform = new Transform({
  position: new Vector3(8, 0, -56),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0143.addComponentOrReplace(floorBaseGrass0143transform)
floorBaseGrass0143.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const islandWalls44 = new Entity("island Walls")
engine.addEntity(islandWalls44)
const islandWalls44transform = new Transform({
  position: new Vector3(48, 0, -48),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
islandWalls44.addComponentOrReplace(islandWalls44transform)
const islandWalls44GLTFShape = new GLTFShape("models/contest4/islandWalls.glb")
islandWalls44GLTFShape.withCollisions = true
islandWalls44GLTFShape.isPointerBlocker = true
islandWalls44GLTFShape.visible = true
islandWalls44.addComponentOrReplace(islandWalls44GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const sleighWithScene45 = new Entity("sleigh With Scene")
engine.addEntity(sleighWithScene45)
const sleighWithScene45transform = new Transform({
  position: new Vector3(40, 0, -80),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
sleighWithScene45.addComponentOrReplace(sleighWithScene45transform)
const sleighWithScene45GLTFShape = new GLTFShape("models/contest6/sleighWithScene.glb")
sleighWithScene45GLTFShape.withCollisions = true
sleighWithScene45GLTFShape.isPointerBlocker = true
sleighWithScene45GLTFShape.visible = true
sleighWithScene45.addComponentOrReplace(sleighWithScene45GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0146 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0146)
const floorBaseGrass0146transform = new Transform({
  position: new Vector3(8, 0, -72),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0146.addComponentOrReplace(floorBaseGrass0146transform)
floorBaseGrass0146.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0147 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0147)
const floorBaseGrass0147transform = new Transform({
  position: new Vector3(8, 0, -88),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0147.addComponentOrReplace(floorBaseGrass0147transform)
floorBaseGrass0147.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0148 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0148)
const floorBaseGrass0148transform = new Transform({
  position: new Vector3(24, 0, -88),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0148.addComponentOrReplace(floorBaseGrass0148transform)
floorBaseGrass0148.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0149 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0149)
const floorBaseGrass0149transform = new Transform({
  position: new Vector3(40, 0, -72),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0149.addComponentOrReplace(floorBaseGrass0149transform)
floorBaseGrass0149.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0150 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0150)
const floorBaseGrass0150transform = new Transform({
  position: new Vector3(40, 0, -88),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0150.addComponentOrReplace(floorBaseGrass0150transform)
floorBaseGrass0150.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const sleighAssetDisplay54 = new Entity("sleigh Asset Display")
engine.addEntity(sleighAssetDisplay54)
const sleighAssetDisplay54transform = new Transform({
  position: new Vector3(11.5, 0, -80),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
sleighAssetDisplay54.addComponentOrReplace(sleighAssetDisplay54transform)
const sleighAssetDisplay54GLTFShape = new GLTFShape("models/contest6/sleighAssetDisplay.glb")
sleighAssetDisplay54GLTFShape.withCollisions = true
sleighAssetDisplay54GLTFShape.isPointerBlocker = true
sleighAssetDisplay54GLTFShape.visible = true
sleighAssetDisplay54.addComponentOrReplace(sleighAssetDisplay54GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const githubLink255 = new Entity("github Link 2")
engine.addEntity(githubLink255)
const githubLink255transform = new Transform({
  position: new Vector3(21.35, 1.25, 8.63),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
githubLink255.addComponentOrReplace(githubLink255transform)
const githubLink255GLTFShape = new GLTFShape("models/common/githubLink.glb")
githubLink255GLTFShape.withCollisions = true
githubLink255GLTFShape.isPointerBlocker = true
githubLink255GLTFShape.visible = true
githubLink255.addComponentOrReplace(githubLink255GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const twitterLink256 = new Entity("twitter Link 2")
engine.addEntity(twitterLink256)
const twitterLink256transform = new Transform({
  position: new Vector3(21.35, 1.25, 7.37),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
twitterLink256.addComponentOrReplace(twitterLink256transform)
const twitterLink256GLTFShape = new GLTFShape("models/common/twitterLink.glb")
twitterLink256GLTFShape.withCollisions = true
twitterLink256GLTFShape.isPointerBlocker = true
twitterLink256GLTFShape.visible = true
twitterLink256.addComponentOrReplace(twitterLink256GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const githubLink357 = new Entity("github Link 3")
engine.addEntity(githubLink357)
const githubLink357transform = new Transform({
  position: new Vector3(21.35, 1.25, -15.37),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
githubLink357.addComponentOrReplace(githubLink357transform)
githubLink357.addComponentOrReplace(githubLink255GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const twitterLink358 = new Entity("twitter Link 3")
engine.addEntity(twitterLink358)
const twitterLink358transform = new Transform({
  position: new Vector3(21.35, 1.25, -16.63),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
twitterLink358.addComponentOrReplace(twitterLink358transform)
twitterLink358.addComponentOrReplace(twitterLink256GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const githubLink459 = new Entity("github Link 4")
engine.addEntity(githubLink459)
const githubLink459transform = new Transform({
  position: new Vector3(21.35, 1.25, -47.38),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
githubLink459.addComponentOrReplace(githubLink459transform)
githubLink459.addComponentOrReplace(githubLink255GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const twitterLink460 = new Entity("twitter Link 4")
engine.addEntity(twitterLink460)
const twitterLink460transform = new Transform({
  position: new Vector3(21.35, 1.25, -48.63),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
twitterLink460.addComponentOrReplace(twitterLink460transform)
twitterLink460.addComponentOrReplace(twitterLink256GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const githubLink661 = new Entity("github Link 6")
engine.addEntity(githubLink661)
const githubLink661transform = new Transform({
  position: new Vector3(21.35, 1.25, -79.37),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
githubLink661.addComponentOrReplace(githubLink661transform)
githubLink661.addComponentOrReplace(githubLink255GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const twitterLink662 = new Entity("twitter Link 6")
engine.addEntity(twitterLink662)
const twitterLink662transform = new Transform({
  position: new Vector3(21.35, 1.25, -80.63),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
twitterLink662.addComponentOrReplace(twitterLink662transform)
twitterLink662.addComponentOrReplace(twitterLink256GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0163 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0163)
const floorBaseGrass0163transform = new Transform({
  position: new Vector3(24, 0, -104),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0163.addComponentOrReplace(floorBaseGrass0163transform)
floorBaseGrass0163.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0164 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0164)
const floorBaseGrass0164transform = new Transform({
  position: new Vector3(24, 0, -120),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0164.addComponentOrReplace(floorBaseGrass0164transform)
floorBaseGrass0164.addComponentOrReplace(floorBaseGrass0121GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const store65 = new Entity("store")
engine.addEntity(store65)
const store65transform = new Transform({
  position: new Vector3(40, 0, -104),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
store65.addComponentOrReplace(store65transform)
const store65GLTFShape = new GLTFShape("models/contest7/store.glb")
store65GLTFShape.withCollisions = true
store65GLTFShape.isPointerBlocker = true
store65GLTFShape.visible = true
store65.addComponentOrReplace(store65GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const githubLink766 = new Entity("github Link 7")
engine.addEntity(githubLink766)
const githubLink766transform = new Transform({
  position: new Vector3(21.35, 1.25, -103.37),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
githubLink766.addComponentOrReplace(githubLink766transform)
githubLink766.addComponentOrReplace(githubLink255GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const twitterLink767 = new Entity("twitter Link 7")
engine.addEntity(twitterLink767)
const twitterLink767transform = new Transform({
  position: new Vector3(21.35, 1.25, -104.63),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
twitterLink767.addComponentOrReplace(twitterLink767transform)
twitterLink767.addComponentOrReplace(twitterLink256GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const wand168 = new Entity("wand1")
engine.addEntity(wand168)
const wand168transform = new Transform({
  position: new Vector3(41.9, 1.27, -102),
  rotation: new Quaternion(0, 0.4226183, 0, -0.9063078),
  scale: new Vector3(1, 1, 1)
})
wand168.addComponentOrReplace(wand168transform)
const wand168GLTFShape = new GLTFShape("models/contest7/wand.glb")
wand168GLTFShape.withCollisions = true
wand168GLTFShape.isPointerBlocker = true
wand168GLTFShape.visible = true
wand168.addComponentOrReplace(wand168GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const wand269 = new Entity("wand2")
engine.addEntity(wand269)
const wand269transform = new Transform({
  position: new Vector3(41.9, 1.27, -102.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
wand269.addComponentOrReplace(wand269transform)
wand269.addComponentOrReplace(wand168GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const scene70 = new Entity("scene")
engine.addEntity(scene70)
const scene70transform = new Transform({
  position: new Vector3(40, 0, 8),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1, 1)
})
scene70.addComponentOrReplace(scene70transform)
const scene70GLTFShape = new GLTFShape("models/contest2/scene.glb")
scene70GLTFShape.withCollisions = true
scene70GLTFShape.isPointerBlocker = true
scene70GLTFShape.visible = true
scene70.addComponentOrReplace(scene70GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const vintagescenewalls71 = new Entity("vintageSceneWalls")
engine.addEntity(vintagescenewalls71)
const vintagescenewalls71transform = new Transform({
  position: new Vector3(40, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
vintagescenewalls71.addComponentOrReplace(vintagescenewalls71transform)
const vintagescenewalls71GLTFShape = new GLTFShape("models/contest2/walls.glb")
vintagescenewalls71GLTFShape.withCollisions = true
vintagescenewalls71GLTFShape.isPointerBlocker = true
vintagescenewalls71GLTFShape.visible = true
vintagescenewalls71.addComponentOrReplace(vintagescenewalls71GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const vintageRecordPlayer72 = new Entity("vintage Record Player")
engine.addEntity(vintageRecordPlayer72)
const vintageRecordPlayer72transform = new Transform({
  position: new Vector3(45.43, 0.973, 8),
  rotation: new Quaternion(0, 0.8660254, 0, -0.5000001),
  scale: new Vector3(0.8, 0.8, 0.8)
})
vintageRecordPlayer72.addComponentOrReplace(vintageRecordPlayer72transform)
const vintageRecordPlayer72GLTFShape = new GLTFShape("models/contest2/vintageRecordPlayer.glb")
vintageRecordPlayer72GLTFShape.withCollisions = true
vintageRecordPlayer72GLTFShape.isPointerBlocker = true
vintageRecordPlayer72GLTFShape.visible = true
vintageRecordPlayer72.addComponentOrReplace(vintageRecordPlayer72GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
  fountain:{
    entity: fountain14,
    transform: fountain14transform,
    GLTFShape: fountain14GLTFShape,
  },
  islandWalls:{
    entity: islandWalls44,
    transform: islandWalls44transform,
    GLTFShape: islandWalls44GLTFShape,
  },
  githubLink2:{
    entity: githubLink255,
    transform: githubLink255transform,
    GLTFShape: githubLink255GLTFShape,
  },
  twitterLink2:{
    entity: twitterLink256,
    transform: twitterLink256transform,
    GLTFShape: twitterLink256GLTFShape,
  },
  githubLink3:{
    entity: githubLink357,
    transform: githubLink357transform,
    GLTFShape: githubLink255GLTFShape,
  },
  twitterLink3:{
    entity: twitterLink358,
    transform: twitterLink358transform,
    GLTFShape: twitterLink256GLTFShape,
  },
  githubLink4:{
    entity: githubLink459,
    transform: githubLink459transform,
    GLTFShape: githubLink255GLTFShape,
  },
  twitterLink4:{
    entity: twitterLink460,
    transform: twitterLink460transform,
    GLTFShape: twitterLink256GLTFShape,
  },
  githubLink6:{
    entity: githubLink661,
    transform: githubLink661transform,
    GLTFShape: githubLink255GLTFShape,
  },
  twitterLink6:{
    entity: twitterLink662,
    transform: twitterLink662transform,
    GLTFShape: twitterLink256GLTFShape,
  },
  store:{
    entity: store65,
    transform: store65transform,
    GLTFShape: store65GLTFShape,
  },
  githubLink7:{
    entity: githubLink766,
    transform: githubLink766transform,
    GLTFShape: githubLink255GLTFShape,
  },
  twitterLink7:{
    entity: twitterLink767,
    transform: twitterLink767transform,
    GLTFShape: twitterLink256GLTFShape,
  },
  wand1:{
    entity: wand168,
    transform: wand168transform,
    GLTFShape: wand168GLTFShape,
  },
  wand2:{
    entity: wand269,
    transform: wand269transform,
    GLTFShape: wand168GLTFShape,
  },
  vintagescenewalls:{
    entity: vintagescenewalls71,
    transform: vintagescenewalls71transform,
    GLTFShape: vintagescenewalls71GLTFShape,
  },
}

